### ISSUE TITLE
No sinister/dexter animations playing

### ISSUE THREAD

**Issue by brnbrito** [busann/op-zerker-unleash#2]
Aye, just tested the module and it seems to work fine, though sinister/dexter show no animation at all, and beast fury seems to cancel itself mid-dash after the 2-3 hit, just wondering what could be wrong

**Comment by kudomine** [comment]
can fix this for update proxy caaali thx

**Comment by kudomine** [comment]
can fix this module for proxy caaali thx

**Comment by busann** [comment]
That is intended so you can run around while in unleash. If the animations play, then it is harder to move. It is also fixed for Caali's proxy.
